package lambda

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent
import java.time.Instant

class KotlinFun : RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
  override fun handleRequest(event: APIGatewayProxyRequestEvent, context: Context): APIGatewayProxyResponseEvent {
    println(
      """
          ${event.headers}
            ###################################################
            ###################################################
            ##                                               ##
            ##                                               ##
            ##           ${Instant.now()}            ##
            ##           LAMBDA RUN GREAT SUCCESS!           ##
            ##                                               ##
            ##                                               ##
            ##                                               ##
            ###################################################
            ###################################################
        """.trimIndent()
    )
    return APIGatewayProxyResponseEvent().apply {
      statusCode = 200
      isBase64Encoded = false
      headers = mapOf(
        "Content-Type" to "text/html"
      )
      body = """
    <!DOCTYPE html>
    <html>
      <head>
        <title>AWS Lambda sample</title>
      </head>
      <body>
        <h1>Welcome</h1>
        <p>Page generated by a Lambda function.</p>
      </body>
    </html>
        """.trimIndent()
    }
  }
}